import { StatusBar } from "expo-status-bar";
import { useState } from "react";
import { Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";

type Mode = "patient" | "clinician";
export default function Home() {
  const [mode, setMode] = useState<Mode>("patient");
  const [email, setEmail] = useState("");
  const [notice, setNotice] = useState("");
  const submit = () => setNotice("Secure sign-in requires configured Supabase authentication. No email or health data was sent.");
  return <SafeAreaView style={styles.safe}><StatusBar style="dark"/><ScrollView contentContainerStyle={styles.page}><Text style={styles.eyebrow}>NeuroAssess</Text><Text style={styles.title}>Your clinic. In your pocket.</Text><Text style={styles.copy}>Use the verified account for your role. Patients enter their private care space; clinicians enter their authorised care workspace.</Text><View style={styles.tabs}>{(["patient","clinician"] as Mode[]).map(item=><Pressable accessibilityRole="tab" key={item} style={[styles.tab,mode===item&&styles.activeTab]} onPress={()=>{setMode(item);setNotice("");}}><Text style={[styles.tabText,mode===item&&styles.activeTabText]}>{item === "patient" ? "Patient" : "Clinician"}</Text></Pressable>)}</View><View style={styles.card}><Text style={styles.cardTitle}>{mode === "patient" ? "Your care portal" : "Your clinical workspace"}</Text><Text style={styles.copy}>{mode === "patient" ? "Appointments, questionnaires, requests, files, and consent are visible only after your secure sign-in." : "Availability, assigned appointments, care requirements, and review queues are restricted to your verified clinic role."}</Text><TextInput accessibilityLabel="Email" autoCapitalize="none" autoComplete="email" keyboardType="email-address" placeholder="Email address" style={styles.input} value={email} onChangeText={setEmail}/><Pressable style={styles.button} onPress={submit}><Text style={styles.buttonText}>Send secure sign-in link</Text></Pressable>{notice ? <Text style={styles.notice}>{notice}</Text> : null}</View><View style={styles.card}><Text style={styles.cardTitle}>Consent-first care</Text><Text style={styles.copy}>Recording and AI assistance remain disabled until a current patient consent decision is verified server-side.</Text></View></ScrollView></SafeAreaView>;
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:"#eef7f2"},page:{padding:24,gap:18},eyebrow:{fontSize:12,fontWeight:"700",letterSpacing:2,color:"#21624f",textTransform:"uppercase"},title:{fontSize:42,lineHeight:47,fontWeight:"700",letterSpacing:-2,color:"#16372f"},copy:{fontSize:15,lineHeight:23,color:"#526a61"},tabs:{flexDirection:"row",gap:8},tab:{paddingHorizontal:18,paddingVertical:10,borderRadius:999,backgroundColor:"#dcebe3"},activeTab:{backgroundColor:"#21624f"},tabText:{fontWeight:"700",color:"#21624f"},activeTabText:{color:"white"},card:{gap:14,padding:20,borderRadius:24,backgroundColor:"rgba(255,255,255,.82)",shadowColor:"#153b30",shadowOpacity:.1,shadowRadius:22,shadowOffset:{width:0,height:12}},cardTitle:{fontSize:20,fontWeight:"700",color:"#16372f"},input:{borderWidth:1,borderColor:"#cbdcd4",borderRadius:12,padding:13,fontSize:16,backgroundColor:"white"},button:{backgroundColor:"#21624f",borderRadius:999,padding:14,alignItems:"center"},buttonText:{color:"white",fontWeight:"700"},notice:{padding:12,borderRadius:12,color:"#215543",backgroundColor:"#dcefe5",lineHeight:20}});
