import { StatusBar } from "expo-status-bar";
import { useState } from "react";
import { Pressable, SafeAreaView, ScrollView, StyleSheet, Switch, Text, View } from "react-native";
import { consentPurposes, type ConsentPurpose } from "@neuroassess/clinical-consent";

const labels: Record<ConsentPurpose, string> = { CONSULTATION_RECORDING: "Consultation recording", AI_CLINICAL_ASSISTANCE: "AI clinical assistance" };
export default function Home() {
  const [consent, setConsent] = useState<Record<ConsentPurpose, boolean>>({ CONSULTATION_RECORDING: false, AI_CLINICAL_ASSISTANCE: false });
  return <SafeAreaView style={styles.safe}><StatusBar style="dark" /><ScrollView contentContainerStyle={styles.page}><Text style={styles.eyebrow}>NeuroAssess</Text><Text style={styles.title}>Care, clearly connected.</Text><Text style={styles.intro}>The iOS, Android and web companion for your NeuroAssess care. Sign in is required before any clinical records or requests are shown.</Text><View style={styles.card}><Text style={styles.cardTitle}>Your choices</Text><Text style={styles.copy}>Recording and AI assistance are off by default. You will make a versioned, auditable choice after secure sign-in. You can withdraw consent at any time.</Text>{consentPurposes.map((purpose) => <View style={styles.row} key={purpose}><View style={styles.rowText}><Text style={styles.label}>{labels[purpose]}</Text><Text style={styles.muted}>Requires your explicit consent</Text></View><Switch value={consent[purpose]} onValueChange={(value) => setConsent({ ...consent, [purpose]: value })} /></View>)}</View><View style={styles.card}><Text style={styles.cardTitle}>Care requests</Text><Text style={styles.copy}>Request a medication refill, follow-up, or medication review securely from your authenticated patient record.</Text><Pressable style={styles.button}><Text style={styles.buttonText}>Sign in to continue</Text></Pressable></View><Text style={styles.footer}>No health, appointment, payment, or clinician data is stored in this app before secure services are connected.</Text></ScrollView></SafeAreaView>;
}
const styles = StyleSheet.create({ safe:{flex:1,backgroundColor:"#eff7f3"},page:{padding:24,gap:18},eyebrow:{fontSize:12,fontWeight:"700",letterSpacing:2,color:"#21624f",textTransform:"uppercase"},title:{fontSize:44,lineHeight:48,fontWeight:"700",letterSpacing:-2,color:"#15322d"},intro:{fontSize:16,lineHeight:25,color:"#50665f"},card:{backgroundColor:"rgba(255,255,255,.75)",padding:20,borderRadius:24,shadowColor:"#173d34",shadowOpacity:.1,shadowRadius:24,shadowOffset:{width:0,height:12},gap:14},cardTitle:{fontSize:20,fontWeight:"700",color:"#15322d"},copy:{fontSize:14,lineHeight:21,color:"#50665f"},row:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",paddingTop:14,borderTopWidth:1,borderColor:"#dce9e2"},rowText:{flex:1,gap:3},label:{fontSize:15,fontWeight:"600",color:"#15322d"},muted:{fontSize:12,color:"#6b7b76"},button:{marginTop:4,backgroundColor:"#21624f",padding:14,borderRadius:99,alignItems:"center"},buttonText:{color:"white",fontWeight:"700"},footer:{fontSize:12,lineHeight:18,color:"#687a73",padding:8}});
