import { Router } from 'express';
import { PatientAssignmentRole, Prisma, Role, TeamQueueStatus, TeamQueueType, UserStatus, WorkflowStage } from '@prisma/client';
import { z } from 'zod';
import { prisma } from '../../shared/db.js';
import { asyncHandler } from '../../shared/http.js';
import { badRequest, notFound } from '../../shared/errors.js';
import { requireAuth, requireRole } from '../../middleware/auth.js';

const router = Router();
router.use(requireAuth, requireRole(Role.ADMIN));
const patientInclude = { user: { select: { id: true, firstName: true, lastName: true, email: true, phone: true, status: true } }, assignments: { where: { active: true }, include: { team: { select: { id: true, code: true, name: true, type: true } }, user: { select: { id: true, firstName: true, lastName: true, roles: true } } } } } satisfies Prisma.PatientInclude;
const recordInclude = { ...patientInclude, appointments: { orderBy: { startsAt: 'desc' }, take: 20 }, assessments: { orderBy: { updatedAt: 'desc' }, take: 20 }, documents: { orderBy: { createdAt: 'desc' }, take: 20 }, physicalReviews: { orderBy: { reviewDate: 'desc' }, take: 20, include: { alerts: true } }, prescriptions: { orderBy: { updatedAt: 'desc' }, take: 20, include: { items: true, statusEvents: { orderBy: { createdAt: 'desc' } } } }, reports: { orderBy: { updatedAt: 'desc' }, take: 20 }, invoices: { orderBy: { updatedAt: 'desc' }, take: 20, include: { payments: true } }, workflowTransitions: { orderBy: { createdAt: 'desc' }, take: 50, include: { team: { select: { code: true, name: true } }, actor: { select: { firstName: true, lastName: true } } } }, queueItems: { where: { status: TeamQueueStatus.OPEN }, include: { team: { select: { code: true, name: true } } } } } satisfies Prisma.PatientInclude;
const assignmentInput = z.object({ teamId: z.string().cuid(), userId: z.string().cuid(), role: z.nativeEnum(PatientAssignmentRole), reason: z.string().trim().min(1).max(500) });

async function audit(actorId: string, action: string, resource: string, resourceId: string, metadata?: Prisma.InputJsonValue) { await prisma.auditEvent.create({ data: { actorId, action, resource, resourceId, metadata } }); }
router.get('/users', asyncHandler(async (_req, res) => { res.json(await prisma.user.findMany({ select: { id: true, email: true, firstName: true, lastName: true, roles: true, status: true, createdAt: true }, orderBy: { createdAt: 'desc' } })); }));
router.patch('/users/:id/status', asyncHandler(async (req, res) => { const status = req.body.status as UserStatus; if (!Object.values(UserStatus).includes(status)) throw badRequest('Invalid user status'); const user = await prisma.user.update({ where: { id: req.params.id }, data: { status } }); await audit(req.user!.id, 'USER_STATUS_UPDATED', 'User', user.id, { status }); res.json(user); }));
router.get('/reports/summary', asyncHandler(async (_req, res) => { const [users, patients, assessments, appointments, invoices] = await Promise.all([prisma.user.count(), prisma.patient.count(), prisma.assessment.count(), prisma.appointment.count(), prisma.invoice.count()]); res.json({ users, patients, assessments, appointments, invoices }); }));
router.get('/command-center', asyncHandler(async (_req, res) => { const [patients, appointments, assessments, openTasks, openComplaints, unreadAudit, queues, transitions] = await Promise.all([prisma.patient.count(), prisma.appointment.count({ where: { status: { in: ['REQUESTED', 'CONFIRMED'] } } }), prisma.assessment.count({ where: { status: { notIn: ['COMPLETE', 'WITHDRAWN'] } } }), prisma.clinicalTask.count({ where: { status: 'OPEN' } }), prisma.complaint.count({ where: { status: { notIn: ['RESOLVED', 'CLOSED'] } } }), prisma.auditEvent.count({ where: { severity: { in: ['WARNING', 'CRITICAL'] } } }), prisma.teamQueueItem.groupBy({ by: ['type'], where: { status: 'OPEN' }, _count: { _all: true } }), prisma.workflowTransition.groupBy({ by: ['toStage'], _count: { _all: true } })]); res.json({ metrics: { patients, appointments, assessments, openTasks, openComplaints, auditAlerts: unreadAudit }, taskQueues: queues.map((item) => ({ type: item.type, count: item._count._all })), workflow: transitions.map((item) => ({ stage: item.toStage, count: item._count._all })) }); }));
router.get('/patients', asyncHandler(async (req, res) => { const query = z.object({ search: z.string().trim().min(1).max(120).optional(), take: z.coerce.number().int().min(1).max(100).default(25) }).parse(req.query); const where = query.search ? { OR: [{ user: { firstName: { contains: query.search, mode: 'insensitive' as const } } }, { user: { lastName: { contains: query.search, mode: 'insensitive' as const } } }, { user: { email: { contains: query.search, mode: 'insensitive' as const } } }] } : {}; res.json(await prisma.patient.findMany({ where, include: patientInclude, orderBy: { updatedAt: 'desc' }, take: query.take })); }));
router.get('/patients/:id/record', asyncHandler(async (req, res) => { const patient = await prisma.patient.findUnique({ where: { id: String(req.params.id) }, include: recordInclude }); if (!patient) throw notFound('Patient not found'); const auditEvents = await prisma.auditEvent.findMany({ where: { OR: [{ resourceId: patient.id }, { resourceId: patient.userId }] }, include: { actor: { select: { firstName: true, lastName: true, email: true } } }, orderBy: { createdAt: 'desc' }, take: 100 }); res.json({ patient, auditEvents }); }));
router.get('/tasks', asyncHandler(async (req, res) => { const query = z.object({ status: z.nativeEnum(TeamQueueStatus).default(TeamQueueStatus.OPEN) }).parse(req.query); res.json(await prisma.teamQueueItem.findMany({ where: { status: query.status }, include: { patient: { include: { user: { select: { firstName: true, lastName: true } } } }, team: { select: { id: true, code: true, name: true } }, assignedTo: { select: { id: true, firstName: true, lastName: true } } }, orderBy: [{ priority: 'desc' }, { dueAt: 'asc' }] })); }));
router.get('/audit', asyncHandler(async (req, res) => { const query = z.object({ patientId: z.string().cuid().optional(), take: z.coerce.number().int().min(1).max(100).default(50) }).parse(req.query); res.json(await prisma.auditEvent.findMany({ where: query.patientId ? { resourceId: query.patientId } : undefined, include: { actor: { select: { firstName: true, lastName: true, email: true } } }, orderBy: { createdAt: 'desc' }, take: query.take })); }));
router.post('/patients/:id/assign', asyncHandler(async (req, res) => { const body = assignmentInput.parse(req.body); const patientId = String(req.params.id); const [patient, member] = await Promise.all([prisma.patient.findUnique({ where: { id: patientId } }), prisma.teamMember.findFirst({ where: { teamId: body.teamId, userId: body.userId, active: true } })]); if (!patient) throw notFound('Patient not found'); if (!member) throw badRequest('Selected user is not an active member of the selected team'); const assignment = await prisma.patientAssignment.create({ data: { patientId, teamId: body.teamId, userId: body.userId, role: body.role, reason: body.reason, assignedById: req.user!.id } }); await audit(req.user!.id, 'PATIENT_ASSIGNED', 'PatientAssignment', assignment.id, { patientId, teamId: body.teamId, userId: body.userId, role: body.role, reason: body.reason }); res.status(201).json(assignment); }));
router.post('/patients/:id/transfer', asyncHandler(async (req, res) => { const body = assignmentInput.extend({ toStage: z.nativeEnum(WorkflowStage), queueType: z.nativeEnum(TeamQueueType).optional(), queueTitle: z.string().trim().min(1).max(200).optional() }).parse(req.body); const patientId = String(req.params.id); const [patient, member, previous] = await Promise.all([prisma.patient.findUnique({ where: { id: patientId } }), prisma.teamMember.findFirst({ where: { teamId: body.teamId, userId: body.userId, active: true } }), prisma.workflowTransition.findFirst({ where: { patientId }, orderBy: { createdAt: 'desc' } })]); if (!patient) throw notFound('Patient not found'); if (!member) throw badRequest('Selected user is not an active member of the receiving team'); const result = await prisma.$transaction(async (tx) => { await tx.patientAssignment.updateMany({ where: { patientId, role: body.role, active: true }, data: { active: false, endsAt: new Date() } }); const assignment = await tx.patientAssignment.create({ data: { patientId, teamId: body.teamId, userId: body.userId, role: body.role, reason: body.reason, assignedById: req.user!.id } }); const transition = await tx.workflowTransition.create({ data: { patientId, teamId: body.teamId, actorId: req.user!.id, fromStage: previous?.toStage, toStage: body.toStage, reason: body.reason, metadata: { assignmentId: assignment.id } } }); if (body.queueType && body.queueTitle) await tx.teamQueueItem.create({ data: { patientId, teamId: body.teamId, assignedToId: body.userId, type: body.queueType, title: body.queueTitle, metadata: { workflowTransitionId: transition.id } } }); return { assignment, transition }; }); await audit(req.user!.id, 'PATIENT_TRANSFERRED', 'Patient', patientId, { fromStage: previous?.toStage ?? null, toStage: body.toStage, teamId: body.teamId, userId: body.userId, reason: body.reason }); res.status(201).json(result); }));
export default router;
