import { Router } from 'express';
import authRoutes from '../modules/auth/auth.routes.js';
import patientRoutes from '../modules/patients/patient.routes.js';
import bookingRoutes from '../modules/booking/booking.routes.js';
import adhdRoutes from '../modules/adhd/adhd.routes.js';
import autismRoutes from '../modules/autism/autism.routes.js';
import clinicalNotesRoutes from '../modules/clinical-notes/clinical-notes.routes.js';
import aiRoutes from '../modules/ai/ai.routes.js';
import billingRoutes from '../modules/billing/billing.routes.js';
import messagingRoutes from '../modules/messaging/messaging.routes.js';
import adminRoutes from '../modules/admin/admin.routes.js';
import videoRoutes from '../modules/video/video.routes.js';
import reportRoutes from '../modules/reports/report.routes.js';
import financeRoutes from '../modules/finance/finance.routes.js';
import portalRoutes from '../modules/portals/portal.routes.js';
import teamRoutes from '../modules/teams/team.routes.js';

const router = Router();
router.get('/health', (_req, res) => res.json({ status: 'ok', service: 'neurocare-backend', timestamp: new Date().toISOString() }));
router.use('/auth', authRoutes);
router.use('/patients', patientRoutes);
router.use('/booking', bookingRoutes);
router.use('/adhd', adhdRoutes);
router.use('/autism', autismRoutes);
router.use('/clinical-notes', clinicalNotesRoutes);
router.use('/ai', aiRoutes);
router.use('/billing', billingRoutes);
router.use('/messages', messagingRoutes);
router.use('/admin', adminRoutes);
router.use('/video', videoRoutes);
router.use('/reports', reportRoutes);
router.use('/finance', financeRoutes);
router.use('/portals', portalRoutes);
router.use('/teams', teamRoutes);
export default router;
