"use client";
import Link from "next/link";
import { useEffect, useState } from "react";

type Snapshot = { states: string[]; rules: { id: string; when: string; next: readonly string[]; description: string }[]; workflow: { state: string; count: number }[]; tasks: { type: string; status: string; count: number }[]; events: { id: string; action: string; resource: string; createdAt: string; actor?: { firstName: string; lastName: string } | null }[] };
const views = ["engine", "workflows", "rules", "events", "states", "tasks"] as const;
const api = process.env.NEXT_PUBLIC_API_BASE_URL ?? "";
export function EngineConsole({ view }: { view: (typeof views)[number] }) { const [data, setData] = useState<Snapshot | null>(null); const [error, setError] = useState<string | null>(null); useEffect(() => { fetch(`${api}/api/v1/engine`, { credentials: "include" }).then(async r => { if (!r.ok) throw new Error(r.status === 401 ? "Sign in with an authorised staff account to access the Engine." : "The Engine data service is unavailable."); return r.json() as Promise<Snapshot>; }).then(setData).catch((e: unknown) => setError(e instanceof Error ? e.message : "The Engine data service is unavailable.")); }, []); const title = view === "engine" ? "NeuroCare Engine" : `${view[0].toUpperCase()}${view.slice(1)} controller`; return <main className="engine"><aside><Link href="/engine" className="engine-brand">n <b>NeuroCare Engine</b></Link><p>CONTROL PLANE</p>{views.map(item => <Link className={item === view ? "selected" : ""} key={item} href={`/${item}`}>{item}</Link>)}<Link href="/admin">← Admin Portal</Link></aside><section><header><div><p className="eyebrow">Shared workflow control plane</p><h1>{title}</h1><p>Rules, states, tasks, events and portal decisions are resolved here. Portals submit commands and render the resulting authorised work.</p></div><button onClick={() => location.assign("/admin")}>Open Admin controller</button></header>{error && <p className="engine-error">{error}</p>}{!data && !error && <p className="engine-loading">Loading authenticated Engine state…</p>}{data && <EngineView data={data} view={view} />}</section></main>; }
function EngineView({ data, view }: { data: Snapshot; view: (typeof views)[number] }) { if (view === "states") return <section className="engine-grid">{data.states.map(state => <article key={state}><small>Workflow state</small><h2>{state.replaceAll("_", " ")}</h2><Link href="/workflows">Inspect transitions →</Link></article>)}</section>; if (view === "rules") return <section className="engine-list">{data.rules.map(rule => <article key={rule.id}><small>WHEN {rule.when}</small><h2>{rule.description}</h2><p>Next: {rule.next.join(" → ")}</p><Link href="/workflows">Open pathway →</Link></article>)}</section>; if (view === "events") return <section className="engine-list">{data.events.map(event => <article key={event.id}><small>{new Date(event.createdAt).toLocaleString()}</small><h2>{event.action.replaceAll("_", " ")}</h2><p>{event.resource} · {event.actor ? `${event.actor.firstName} ${event.actor.lastName}` : "System"}</p></article>)}</section>; const items = view === "tasks" ? data.tasks.map(item => ({ title: item.type.replaceAll("_", " "), value: item.count, label: item.status })) : data.workflow.map(item => ({ title: item.state.replaceAll("_", " "), value: item.count, label: "Active cases" })); return <section className="engine-grid">{items.map(item => <article key={`${item.title}-${item.label}`}><small>{item.label}</small><strong>{item.value}</strong><h2>{item.title}</h2><Link href="/admin">Control from Admin →</Link></article>)}</section>; }
