"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";

export const portalConfig = {
  patient: { label: "Patient", roles: "PATIENT", title: "Your care, connected", summary: "Appointments, documents, messages, medication and billing in one private care space.", queues: ["Upcoming appointment", "Care tasks", "Documents shared", "Medication tracker"] },
  clinician: { label: "Clinician", roles: "PSYCHIATRIST · NURSE", title: "Clinical care, in focus", summary: "Prioritised assessments, patient context and safe handoffs for the current clinical team.", queues: ["Assessment queue", "Appointments today", "Reports for review", "Priority patients"] },
  titration: { label: "Titration", roles: "NURSE · PRESCRIBER", title: "Medication review, connected", summary: "Dose history, side-effect monitoring, physical health and prescriber handoff in one queue.", queues: ["Reviews due", "Side-effect monitoring", "Physical health alerts", "Prescriber handoffs"] },
  prescriber: { label: "Prescriber", roles: "PSYCHIATRIST · PRESCRIBER", title: "Safe prescribing, in focus", summary: "Prescription approval, issuing, dispatch and shared-care decisions with a complete audit trail.", queues: ["Awaiting approval", "Prescription issues", "Courier updates", "Shared-care requests"] },
  admin: { label: "Admin", roles: "ADMIN", title: "Clinic operations, connected", summary: "Bookings, users, governance and operational decisions without duplicating clinical workflows.", queues: ["Booking management", "Access requests", "Governance reviews", "Audit exceptions"] },
  finance: { label: "Finance", roles: "FINANCE · ADMIN", title: "Finance, without blind spots", summary: "Invoices, payments, earnings and service performance in the same governed platform.", queues: ["Outstanding invoices", "Payment plans", "Clinician earnings", "Revenue exceptions"] },
  platform: { label: "Platform", roles: "SUPER_ADMIN", title: "Platform control, governed", summary: "Tenant policy, access governance, feature controls and platform-wide audit intelligence.", queues: ["Tenant health", "Access governance", "AI policy reviews", "Critical audit events"] },
} as const;
export type Portal = keyof typeof portalConfig;
const nav = Object.entries(portalConfig) as [Portal, (typeof portalConfig)[Portal]][];
const stages = ["Referral", "Booking", "Assessment", "Titration", "Prescribing", "Shared care", "Discharge"];

export function PlatformShell({ portal }: { portal: Portal }) {
  const pathname = usePathname(); const config = portalConfig[portal];
  return <main className="shell"><aside className="sidebar"><Link className="brand" href="/patient"><span>n</span><b>NeuroCare</b></Link><p className="tenant">Enterprise platform</p><nav>{nav.map(([key, item]) => <Link key={key} className={pathname === `/${key}` ? "active" : ""} href={`/${key}`}>{item.label}</Link>)}</nav><div className="sidebar-footer"><button aria-label="Global notifications">Notifications <strong>0</strong></button><button aria-label="Global search">Search</button><small>Access is role-scoped and audited.</small></div></aside><section className="content"><header><div><p className="eyebrow">{config.roles} workspace</p><div className="crumbs"><Link href={`/${portal}`}>Home</Link><span>/</span><span>{config.label}</span></div><h1>{config.title}</h1><p className="muted">{config.summary}</p></div><div className="header-actions"><button>Search records</button><button className="primary">New action</button></div></header><section className="journey"><div><p className="eyebrow">Patient journey engine</p><h2>One pathway, clear ownership</h2></div><ol>{stages.map((stage, index) => <li className={index < 3 ? "complete" : ""} key={stage}><i>{index + 1}</i>{stage}</li>)}</ol></section><section className="section-heading"><div><p className="eyebrow">Action queues</p><h2>{config.label} worklist</h2></div><button>View all records</button></section><section className="cards">{config.queues.map((queue) => <article key={queue}><p className="eyebrow">Assigned to your role</p><strong>0</strong><h3>{queue}</h3><p className="muted">Live records will be supplied by the shared API and filtered by patient assignment.</p><button>Open queue →</button></article>)}</section><section className="grid"><article className="panel"><p className="eyebrow">Patient timeline</p><h2>Related care activity</h2><div className="empty">Select a patient to view their assessments, care-team transfers, medication decisions, documents and messages in one chronological timeline.</div></article><article className="panel"><p className="eyebrow">Transfer engine</p><h2>Ownership and audit</h2><div className="empty">Transfers must record the originating team, receiving team, actor, reason and timestamp before a queue assignment changes.</div></article></section><footer>All actions are routed through the shared API, permissions engine and audit trail.</footer></section></main>;
}
