import { TeamQueueStatus, TeamQueueType, WorkflowStage } from '@prisma/client';
import { prisma } from '../../shared/db.js';
import { badRequest, notFound } from '../../shared/errors.js';

export const engineStates = Object.values(WorkflowStage);
export const engineRules = [
  { id: 'assessment-complete', when: 'ASSESSMENT_COMPLETE', next: ['OUTCOME', 'MORE_INFORMATION_REQUIRED', 'ECG_REQUESTED', 'DISCHARGE'], description: 'Assessment completion requires an explicit clinical outcome.' },
  { id: 'adhd-confirmed', when: 'ADHD_CONFIRMED', next: ['TITRATION', 'PRESCRIBING'], description: 'Confirmed ADHD opens medication review or prescribing.' },
  { id: 'ecg-required', when: 'ECG_REQUESTED', next: ['PATIENT_TASK'], description: 'Request an ECG document and pause progression until it is received.' },
  { id: 'ecg-received', when: 'ECG_RECEIVED', next: ['ASSESSMENT_REVIEW'], description: 'A verified ECG reopens assessment review.' },
  { id: 'discharge', when: 'DISCHARGE', next: ['LETTER', 'CASE_CLOSED'], description: 'Discharge creates a letter task before case closure.' },
] as const;

export async function snapshot() { const [workflow, queues, events] = await Promise.all([prisma.workflowTransition.groupBy({ by: ['toStage'], _count: { _all: true } }), prisma.teamQueueItem.groupBy({ by: ['type', 'status'], _count: { _all: true } }), prisma.auditEvent.findMany({ orderBy: { createdAt: 'desc' }, take: 25, include: { actor: { select: { firstName: true, lastName: true } } } })]); return { states: engineStates, rules: engineRules, workflow: workflow.map((x) => ({ state: x.toStage, count: x._count._all })), tasks: queues.map((x) => ({ type: x.type, status: x.status, count: x._count._all })), events }; }
export async function transition(input: { patientId: string; actorId: string; toStage: WorkflowStage; reason: string; teamId?: string; queue?: { type: TeamQueueType; title: string; assignedToId?: string; dueAt?: Date } }) { const [patient, previous] = await Promise.all([prisma.patient.findUnique({ where: { id: input.patientId } }), prisma.workflowTransition.findFirst({ where: { patientId: input.patientId }, orderBy: { createdAt: 'desc' } })]); if (!patient) throw notFound('Patient not found'); return prisma.$transaction(async (tx) => { const workflow = await tx.workflowTransition.create({ data: { patientId: input.patientId, actorId: input.actorId, teamId: input.teamId, fromStage: previous?.toStage, toStage: input.toStage, reason: input.reason } }); const task = input.queue && input.teamId ? await tx.teamQueueItem.create({ data: { patientId: input.patientId, teamId: input.teamId, assignedToId: input.queue.assignedToId, type: input.queue.type, title: input.queue.title, dueAt: input.queue.dueAt, metadata: { workflowId: workflow.id } } }) : null; await tx.auditEvent.create({ data: { actorId: input.actorId, action: 'ENGINE_WORKFLOW_TRANSITIONED', resource: 'Patient', resourceId: input.patientId, metadata: { from: previous?.toStage ?? null, to: input.toStage, workflowId: workflow.id, taskId: task?.id ?? null } } }); return { workflow, task, next: nextActions(input.toStage) }; }); }
export async function completeTask(input: { taskId: string; actorId: string }) { const task = await prisma.teamQueueItem.findUnique({ where: { id: input.taskId } }); if (!task) throw notFound('Engine task not found'); if (task.status === TeamQueueStatus.COMPLETED) throw badRequest('Engine task is already completed'); return prisma.$transaction(async (tx) => { const updated = await tx.teamQueueItem.update({ where: { id: task.id }, data: { status: TeamQueueStatus.COMPLETED } }); await tx.auditEvent.create({ data: { actorId: input.actorId, action: 'ENGINE_TASK_COMPLETED', resource: 'TeamQueueItem', resourceId: task.id, metadata: { patientId: task.patientId, type: task.type } }); return updated; }); }
export function nextActions(state: WorkflowStage) { return ({ REFERRAL: ['ADMIN_TRIAGE', 'ASSESSMENT'], ASSESSMENT: ['OUTCOME', 'MORE_INFORMATION_REQUIRED', 'ECG_REQUESTED'], OUTCOME: ['TITRATION', 'PRESCRIBING', 'DISCHARGE'], ECG_REQUESTED: ['PATIENT_TASK', 'ASSESSMENT_REVIEW'], TITRATION: ['PRESCRIBING', 'SHARED_CARE'], PRESCRIBING: ['SHARED_CARE', 'DISCHARGE'], SHARED_CARE: ['DISCHARGE'], DISCHARGE: ['LETTER', 'CASE_CLOSED'] } as Partial<Record<WorkflowStage, string[]>>)[state] ?? []; }
