import { TeamQueueStatus, TeamQueueType, WorkflowStage } from '@prisma/client';
import { prisma } from '../../shared/db.js';
import { badRequest, notFound } from '../../shared/errors.js';

export const engineStates = Object.values(WorkflowStage);
type Rule = { id: string; from: WorkflowStage[]; to: WorkflowStage[]; description: string };
export const engineRules: Rule[] = [
  { id: 'referral-intake', from: [WorkflowStage.REFERRAL, WorkflowStage.ADMIN_TRIAGE], to: [WorkflowStage.ASSESSMENT, WorkflowStage.MORE_INFORMATION_REQUIRED], description: 'Referral triage opens assessment or requests missing information.' },
  { id: 'assessment-outcome', from: [WorkflowStage.ASSESSMENT, WorkflowStage.ASSESSMENT_REVIEW], to: [WorkflowStage.OUTCOME, WorkflowStage.MORE_INFORMATION_REQUIRED, WorkflowStage.ECG_REQUESTED], description: 'Assessment review records an explicit outcome or creates a required-information task.' },
  { id: 'outcome-pathways', from: [WorkflowStage.OUTCOME], to: [WorkflowStage.TITRATION, WorkflowStage.PRESCRIBING, WorkflowStage.DISCHARGE], description: 'An authorised outcome opens medication, prescribing, or discharge pathways.' },
  { id: 'ecg-return', from: [WorkflowStage.ECG_REQUESTED], to: [WorkflowStage.ASSESSMENT_REVIEW], description: 'ECG verification reopens assessment review.' },
  { id: 'medication-pathways', from: [WorkflowStage.TITRATION, WorkflowStage.PRESCRIBING], to: [WorkflowStage.PRESCRIBING, WorkflowStage.SHARED_CARE, WorkflowStage.DISCHARGE], description: 'Medication care progresses to prescribing, shared care, or discharge.' },
  { id: 'case-close', from: [WorkflowStage.SHARED_CARE], to: [WorkflowStage.DISCHARGE], description: 'Shared care can proceed to discharge after required care actions are complete.' },
];

const generatedTask: Partial<Record<WorkflowStage, { type: TeamQueueType; title: string }>> = {
  [WorkflowStage.ECG_REQUESTED]: { type: TeamQueueType.MISSING_DOCUMENT, title: 'Pending ECG upload and verification' },
  [WorkflowStage.MORE_INFORMATION_REQUIRED]: { type: TeamQueueType.AWAITING_INFORMATION, title: 'Awaiting clinical information' },
  [WorkflowStage.TITRATION]: { type: TeamQueueType.ACTIVE_TITRATION, title: 'Active titration review' },
  [WorkflowStage.PRESCRIBING]: { type: TeamQueueType.PRESCRIPTION_AWAITING_APPROVAL, title: 'Pending prescription review' },
  [WorkflowStage.SHARED_CARE]: { type: TeamQueueType.AWAITING_REPORT, title: 'Pending shared care letter' },
  [WorkflowStage.DISCHARGE]: { type: TeamQueueType.AWAITING_REPORT, title: 'Pending discharge letter' },
};

export async function snapshot() { const [workflow, queues, events] = await Promise.all([prisma.workflowTransition.groupBy({ by: ['toStage'], _count: { _all: true } }), prisma.teamQueueItem.groupBy({ by: ['type', 'status'], _count: { _all: true } }), prisma.auditEvent.findMany({ orderBy: { createdAt: 'desc' }, take: 25, include: { actor: { select: { firstName: true, lastName: true } } } })]); return { states: engineStates, rules: engineRules, workflow: workflow.map((x) => ({ state: x.toStage, count: x._count._all })), tasks: queues.map((x) => ({ type: x.type, status: x.status, count: x._count._all })), events }; }
export async function transition(input: { patientId: string; actorId: string; toStage: WorkflowStage; reason: string; teamId?: string; queue?: { type: TeamQueueType; title: string; assignedToId?: string; dueAt?: Date } }) { const [patient, previous] = await Promise.all([prisma.patient.findUnique({ where: { id: input.patientId } }), prisma.workflowTransition.findFirst({ where: { patientId: input.patientId }, orderBy: { createdAt: 'desc' } })]); if (!patient) throw notFound('Patient not found'); const rule = previous?.toStage ? engineRules.find((candidate) => candidate.from.includes(previous.toStage!) && candidate.to.includes(input.toStage)) : input.toStage === WorkflowStage.REFERRAL ? engineRules[0] : undefined; if (!rule) throw badRequest(`Engine rule does not permit transition from ${previous?.toStage ?? 'INITIAL'} to ${input.toStage}`); const queue = input.queue ?? (input.teamId && generatedTask[input.toStage] ? { ...generatedTask[input.toStage] } : undefined); return prisma.$transaction(async (tx) => { const workflow = await tx.workflowTransition.create({ data: { patientId: input.patientId, actorId: input.actorId, teamId: input.teamId, fromStage: previous?.toStage, toStage: input.toStage, reason: input.reason, metadata: { ruleId: rule.id } } }); const task = queue && input.teamId ? await tx.teamQueueItem.create({ data: { patientId: input.patientId, teamId: input.teamId, assignedToId: queue.assignedToId, type: queue.type, title: queue.title, dueAt: queue.dueAt, metadata: { workflowId: workflow.id, ruleId: rule.id } } }) : null; await tx.auditEvent.create({ data: { actorId: input.actorId, action: 'ENGINE_WORKFLOW_TRANSITIONED', resource: 'Patient', resourceId: input.patientId, metadata: { from: previous?.toStage ?? null, to: input.toStage, workflowId: workflow.id, taskId: task?.id ?? null, ruleId: rule.id } } }); return { workflow, task, next: nextActions(input.toStage) }; }); }
export async function completeTask(input: { taskId: string; actorId: string }) { const task = await prisma.teamQueueItem.findUnique({ where: { id: input.taskId } }); if (!task) throw notFound('Engine task not found'); if (task.status === TeamQueueStatus.COMPLETED) throw badRequest('Engine task is already completed'); return prisma.$transaction(async (tx) => { const updated = await tx.teamQueueItem.update({ where: { id: task.id }, data: { status: TeamQueueStatus.COMPLETED } }); await tx.auditEvent.create({ data: { actorId: input.actorId, action: 'ENGINE_TASK_COMPLETED', resource: 'TeamQueueItem', resourceId: task.id, metadata: { patientId: task.patientId, type: task.type } }); return updated; }); }
export function nextActions(state: WorkflowStage) { return engineRules.filter((rule) => rule.from.includes(state)).flatMap((rule) => rule.to); }
