"use client";
import { FormEvent, useState } from "react";

type View = "today" | "patients" | "availability" | "review";
export default function Page() {
  const [view, setView] = useState<View>("today"); const [notice,setNotice] = useState("");
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setNotice("Availability will update the shared clinic schedule after your verified clinician account and tenant storage are connected."); };
  return <main className="portal"><header className="topbar"><div><p className="eyebrow">NeuroAssess · clinician</p><h1>Your clinical workspace</h1></div><button className="quiet" onClick={()=>setView("availability")}>Set availability</button></header><nav className="nav" aria-label="Clinician portal">{(["today","patients","availability","review"] as View[]).map(item=><button key={item} onClick={()=>setView(item)} className={view===item?"active":""}>{item === "today" ? "Today" : item === "patients" ? "My patients" : item === "availability" ? "Calendar" : "Review queue"}</button>)}</nav>{view === "today" && <><section className="hero"><p className="eyebrow">Clinical focus</p><h2>Your day, without the noise.</h2><p>See only your assigned appointments, new patient submissions, and follow-ups. Patient files open from the appointment or your assigned list.</p><button onClick={()=>setView("patients")}>Open my patients</button></section><section className="two"><article className="glass"><p className="eyebrow">Next appointment</p><h2>Nothing scheduled</h2><p className="muted">Assigned appointments synchronise here after clinic scheduling is connected.</p></article><article className="glass"><p className="eyebrow">New information</p><h2>No new submissions</h2><p className="muted">Patient uploads and completed requirements appear here for review.</p></article></section></>}{view === "patients" && <section className="glass"><p className="eyebrow">Patient files</p><h2>Your assigned patients</h2><p className="muted">Open a patient file to review appointment intake, questionnaires, documents, consent, timeline and follow-up requirements. You cannot access patients outside your assignment or clinic.</p><div className="empty">No patient files are assigned to you.</div></section>}{view === "availability" && <section className="glass"><p className="eyebrow">Calendar</p><h2>Set availability</h2><p className="muted">Your availability is shared with authorised clinic scheduling staff. Confirmed appointments then synchronise to your workspace and the patient portal.</p><form onSubmit={submit}><label>Available from<input required type="datetime-local" /></label><label>Available until<input required type="datetime-local" /></label><button type="submit">Save availability</button></form>{notice && <p className="notice">{notice}</p>}</section>}{view === "review" && <section className="glass"><p className="eyebrow">Clinical review</p><h2>One queue for patient information</h2><p className="muted">New questionnaires, informant reports, physical-health observations, documents and follow-up responses move here once submitted. Review and clinical decisions stay with you.</p><div className="empty">No cases are awaiting review.</div></section>}<footer>Recording, AI assistance and prescribing actions require verified consent, assignment, and clinician approval.</footer></main>;
}
