"use client";
import { FormEvent, useEffect, useState } from "react";

type WorkItem = { id: string; kind: string; patientId: string | null; patientName: string; title: string; dueAt: string | null };
type Today = Record<"todayAppointments" | "waitingPatients" | "activeTitrations" | "pendingReports" | "pendingPrescriptions" | "messages" | "urgentReviews" | "upcomingFollowUps", WorkItem[]>;
type Patient = Record<string, any>;
const api = process.env.NEXT_PUBLIC_API_BASE_URL ?? "";
const sections: { key: keyof Today; label: string }[] = [
  { key: "todayAppointments", label: "Today's Appointments" }, { key: "waitingPatients", label: "Waiting Patients" }, { key: "activeTitrations", label: "Active Titrations" }, { key: "pendingReports", label: "Pending Reports" },
  { key: "pendingPrescriptions", label: "Pending Prescriptions" }, { key: "messages", label: "Messages" }, { key: "urgentReviews", label: "Urgent Reviews" }, { key: "upcomingFollowUps", label: "Upcoming Follow-ups" },
];
const tabs = ["Overview", "Timeline", "Assessment", "ADHD", "ASD", "Physical Health", "Documents", "Messages", "Reports", "Prescriptions", "Billing", "Tasks"] as const;
const reportTypes = ["Consultation note", "ADHD report", "ASD report", "GP letter", "Shared Care letter"];

async function request<T>(path: string, init?: RequestInit): Promise<T> {
  const response = await fetch(`${api}/api/v1${path}`, { credentials: "include", headers: { "content-type": "application/json", ...(init?.headers ?? {}) }, ...init });
  if (!response.ok) throw new Error(response.status === 401 ? "Sign in with your clinician account." : "The clinical service is unavailable.");
  return response.json() as Promise<T>;
}
const name = (patient: Patient) => `${patient.user?.firstName ?? "Patient"} ${patient.user?.lastName ?? ""}`.trim();
const date = (value?: string | null) => value ? new Intl.DateTimeFormat("en-GB", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "No date";
const money = (pence: number) => new Intl.NumberFormat("en-GB", { style: "currency", currency: "GBP" }).format(pence / 100);

export default function Page() {
  const [today, setToday] = useState<Today | null>(null), [selected, setSelected] = useState<Patient | null>(null), [tab, setTab] = useState<(typeof tabs)[number]>("Overview"), [error, setError] = useState<string | null>(null), [loading, setLoading] = useState(true);
  const loadToday = () => request<Today>("/clinician/today").then(setToday).catch(e => setError(e.message)).finally(() => setLoading(false));
  useEffect(() => { void loadToday(); }, []);
  const openPatient = async (patientId: string | null) => { if (!patientId) return; setError(null); try { setSelected(await request<Patient>(`/clinician/patients/${patientId}/workspace`)); setTab("Overview"); } catch (e) { setError(e instanceof Error ? e.message : "Unable to open patient workspace."); } };
  if (selected) return <PatientWorkspace patient={selected} tab={tab} setTab={setTab} close={() => { setSelected(null); loadToday(); }} setError={setError} />;
  return <main className="station"><header className="station-header"><div><p className="eyebrow">Clinician Station</p><h1>My Clinic Today</h1><p>Open a patient to review, document and progress care.</p></div><button className="quiet" onClick={loadToday}>Refresh worklist</button></header>{error && <p className="notice">{error}</p>}{loading && <p className="loading">Loading your authorised clinic worklist…</p>}<section className="worklists">{today && sections.map(section => <section className="worklist" key={section.key}><div className="worklist-heading"><h2>{section.label}</h2><span>{today[section.key].length}</span></div>{today[section.key].length ? <ul>{today[section.key].map(item => <li key={`${section.key}-${item.id}`}><button onClick={() => openPatient(item.patientId)} disabled={!item.patientId}><strong>{item.patientName}</strong><span>{item.title}</span><small>{date(item.dueAt)}</small></button></li>)}</ul> : <p className="empty">No items requiring your attention.</p>}</section>)}</section></main>;
}

function PatientWorkspace({ patient, tab, setTab, close, setError }: { patient: Patient; tab: (typeof tabs)[number]; setTab: (tab: (typeof tabs)[number]) => void; close: () => void; setError: (error: string | null) => void }) {
  const [note, setNote] = useState(""), [copilot, setCopilot] = useState(""), [draftType, setDraftType] = useState(reportTypes[0]), [saving, setSaving] = useState(false), [earnings, setEarnings] = useState<Patient[]>([]);
  useEffect(() => { request<{ earnings: Patient[] }>("/finance/earnings/me").then(result => setEarnings(result.earnings)).catch(() => undefined); }, []);
  const saveNote = async () => { if (!note.trim()) return; setSaving(true); try { await request("/clinical-notes", { method: "POST", body: JSON.stringify({ patientId: patient.id, type: "CONSULTATION", content: note }) }); setNote(""); } catch (e) { setError(e instanceof Error ? e.message : "Unable to save note."); } finally { setSaving(false); } };
  const scheduleFollowUp = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); setSaving(true); try { await request(`/clinician/patients/${patient.id}/follow-ups`, { method: "POST", body: JSON.stringify({ interval: form.get("interval"), dueAt: form.get("dueAt") || undefined, note: form.get("note") || undefined }) }); event.currentTarget.reset(); } catch (e) { setError(e instanceof Error ? e.message : "Unable to schedule follow-up."); } finally { setSaving(false); } };
  const saveOverview = async (medicalHistory: string, currentMedication: string) => { setSaving(true); try { await request(`/clinician/patients/${patient.id}`, { method: "PATCH", body: JSON.stringify({ medicalHistory, currentMedication: currentMedication ? JSON.parse(currentMedication) : [] }) }); } catch (e) { setError(e instanceof Error ? e.message : "Unable to save overview."); } finally { setSaving(false); } };
  return <main className="workspace"><header className="workspace-header"><button className="quiet" onClick={close}>← My Clinic Today</button><div><p className="eyebrow">Patient Workspace</p><h1>{name(patient)}</h1><p>{patient.user?.email} · all clinical changes are auditable</p></div></header><nav className="tabs">{tabs.map(item => <button className={tab === item ? "active" : ""} onClick={() => setTab(item)} key={item}>{item}</button>)}</nav><section className="panels"><article className="panel"><WorkspaceTab patient={patient} tab={tab} note={note} setNote={setNote} saveNote={saveNote} saving={saving} saveOverview={saveOverview} /></article><aside className="panel actions"><AiCopilot draftType={draftType} setDraftType={setDraftType} value={copilot} setValue={setCopilot} /><form className="followup" onSubmit={scheduleFollowUp}><h2>Follow-up Engine</h2><label>Interval<select name="interval" defaultValue="4w"><option value="2w">2 weeks</option><option value="4w">4 weeks</option><option value="6w">6 weeks</option><option value="3m">3 months</option><option value="6m">6 months</option><option value="custom">Custom</option></select></label><label>Custom due date<input name="dueAt" type="datetime-local" /></label><label>Clinical note<textarea name="note" rows={2} /></label><button className="primary" disabled={saving}>Create appointment task and reminder</button></form><Earnings earnings={earnings} /></aside></section></main>;
}

function WorkspaceTab({ patient, tab, note, setNote, saveNote, saving, saveOverview }: any) {
  const sources: Record<string, any[]> = { Timeline: patient.workflowTransitions, Assessment: patient.assessments, ADHD: patient.assessments?.filter((x: any) => x.type === "ADHD"), ASD: patient.assessments?.filter((x: any) => x.type === "AUTISM"), "Physical Health": patient.physicalReviews, Documents: patient.documents, Messages: patient.messageThreads, Reports: patient.reports, Prescriptions: patient.prescriptions, Billing: patient.invoices, Tasks: patient.queueItems };
  if (tab === "Overview") return <Overview patient={patient} saving={saving} saveOverview={saveOverview}><h2>Consultation notes</h2><textarea value={note} onChange={e => setNote(e.target.value)} placeholder="Write an editable clinical note…" rows={9} /><button className="primary" onClick={saveNote} disabled={saving}>Save clinical note</button><RecordList items={patient.notes} /></Overview>;
  const items = sources[tab] ?? [];
  return <><h2>{tab}</h2><p className="muted">Open records are scoped to your clinician assignment. Use the editable consultation note and Copilot panels to create reviewed clinical content.</p><RecordList items={items} /></>;
}
function Overview({ patient, saving, saveOverview, children }: any) { const [medicalHistory, setMedicalHistory] = useState(patient.medicalHistory ?? ""); const [medication, setMedication] = useState(JSON.stringify(patient.currentMedication ?? [], null, 2)); return <><h2>Overview</h2><div className="details"><label>Medical history<textarea value={medicalHistory} onChange={e => setMedicalHistory(e.target.value)} rows={4} /></label><label>Current medication (JSON)<textarea value={medication} onChange={e => setMedication(e.target.value)} rows={4} /></label></div><button className="primary" onClick={() => saveOverview(medicalHistory, medication)} disabled={saving}>Save overview</button>{children}</>; }
function RecordList({ items = [] }: { items?: any[] }) { return items.length ? <ul className="records">{items.map(item => <li key={item.id}><strong>{item.title ?? item.status ?? item.type ?? item.eventType ?? "Clinical record"}</strong><span>{item.content ?? item.reason ?? item.number ?? "Open in connected record"}</span><small>{date(item.updatedAt ?? item.createdAt ?? item.reviewDate ?? item.startsAt)}</small></li>)}</ul> : <p className="empty">No authorised records in this section.</p>; }
function AiCopilot({ draftType, setDraftType, value, setValue }: any) { const [busy, setBusy] = useState(false), [error, setError] = useState<string | null>(null); const run = async (action: string) => { if (!value.trim()) return; setBusy(true); setError(null); try { const output = await request<{ content: string }>("/ai/copilot", { method: "POST", body: JSON.stringify({ action, text: value }) }); setValue(output.content); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to generate an AI draft."); } finally { setBusy(false); } }; return <section className="copilot"><p className="eyebrow">AI Copilot</p><h2>Editable clinician draft</h2><label>Draft type<select value={draftType} onChange={e => setDraftType(e.target.value)}>{reportTypes.map(type => <option key={type}>{type}</option>)}</select></label><textarea value={value} onChange={e => setValue(e.target.value)} placeholder="Paste consultation notes or a reviewed transcript. All output remains editable and requires clinician review." rows={9} /><div className="button-row"><button type="button" onClick={() => run("LISTEN")} disabled={busy}>Listen to consultation</button><button type="button" onClick={() => run("NOTES")} disabled={busy}>Generate notes</button><button type="button" onClick={() => run(draftType === "ADHD report" ? "ADHD_REPORT" : draftType === "ASD report" ? "ASD_REPORT" : draftType === "GP letter" ? "GP_LETTER" : "SHARED_CARE_LETTER")} disabled={busy}>Generate report / letter</button><button type="button" onClick={() => run("REWRITE")} disabled={busy}>Rewrite</button><button type="button" onClick={() => run("SHORTEN")} disabled={busy}>Shorten</button><button type="button" onClick={() => run("EXPAND")} disabled={busy}>Expand</button><button type="button" onClick={() => run("IMPROVE_WORDING")} disabled={busy}>Improve wording</button></div>{error && <p className="notice">{error}</p>}<small>Listening requires a configured, consented transcription provider; this panel never finalises AI output.</small></section>; }
function Earnings({ earnings }: { earnings: Patient[] }) { const totals = earnings.reduce((sum, entry) => ({ amount: sum.amount + (entry.amountPence ?? 0), paid: sum.paid + (entry.paidAmountPence ?? 0), due: sum.due + (entry.dueAmountPence ?? 0), assessments: sum.assessments + (entry.assessments ?? 0), reviews: sum.reviews + (entry.reviews ?? 0), reports: sum.reports + (entry.reports ?? 0) }), { amount: 0, paid: 0, due: 0, assessments: 0, reviews: 0, reports: 0 }); return <section className="earnings"><p className="eyebrow">My earnings</p><h2>Clinician Earnings</h2><dl><div><dt>Daily / weekly / monthly</dt><dd>{money(totals.amount)}</dd></div><div><dt>Outstanding payments</dt><dd>{money(totals.due)}</dd></div><div><dt>Assessments / reviews / reports</dt><dd>{totals.assessments} / {totals.reviews} / {totals.reports}</dd></div></dl><small>Only your own earnings are returned by the clinician earnings service.</small></section>; }
